// The calendar subscription feed, /calendar.ics.
//
// For this finished 2023 edition the feed is a STATIC file, committed at
// public/calendar.ics and generated by scripts/build-calendar.mjs, NOT a Netlify
// function. ESPN's fiba slug serves no 2023 event, so there is nothing to fetch
// live; the old per-request function returned a hard 502 in production. These tests
// guard two things: that the committed file has not drifted from the generator, and
// that it carries the right shape and identity for a subscriber's calendar.
//
// scripts/** sits outside the coverage gate family-wide, so importing the generator
// here does not pull it into the 100% include; the app's own utils/ics.js (which
// actually writes the events) stays covered by test/utils.test.js.

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { describe, it, expect } from 'vitest'
import { buildCalendar } from '../scripts/build-calendar.mjs'
import { GAMES } from '../src/data/games.js'

const FEED_PATH = join(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'calendar.ics')
const committed = readFileSync(FEED_PATH, 'utf8')
const generated = buildCalendar()

describe('static calendar feed', () => {
  it('the committed file is in sync with the generator', () => {
    // If this fails, run `npm run build:calendar` and commit public/calendar.ics.
    expect(committed).toBe(generated)
  })

  it('is a single VCALENDAR with one VEVENT per game', () => {
    expect(committed.startsWith('BEGIN:VCALENDAR')).toBe(true)
    expect(committed.trimEnd().endsWith('END:VCALENDAR')).toBe(true)
    expect(committed.match(/BEGIN:VEVENT/g)).toHaveLength(GAMES.length)
    expect(committed.match(/END:VEVENT/g)).toHaveLength(GAMES.length)
  })

  it('carries this edition\'s identity, not a sibling\'s', () => {
    expect(committed).toContain("PRODID:-//FIBA Men's World Cup 2023 Viewer//EN")
    expect(committed).toContain("X-WR-CALNAME:FIBA Men's World Cup 2023")
    expect(committed).toContain('UID:fibamwc2023-game-1@fibamensworldcupviewer')
  })

  it('stamps every event with the frozen DTSTAMP, so the file is deterministic', () => {
    const stamps = committed.match(/DTSTAMP:\S+/g)
    expect(stamps).toHaveLength(GAMES.length)
    expect(new Set(stamps)).toEqual(new Set(['DTSTAMP:20230911T000000Z']))
  })

  it('bakes in the real final scores, away-first', () => {
    // Game 1: Angola vs Italy 67-81 (Italy won). The summary orders the game the way
    // the app does and appends the final score.
    expect(committed).toContain('SUMMARY:FIBA MWC: Angola vs Italy (67–81)')
    // The 2023 Final: Germany beat Serbia 83-77.
    expect(committed).toContain('SUMMARY:FIBA MWC: Germany vs Serbia (83–77)')
  })

  it('has no all-day events: every 2023 game has a known tip-off time', () => {
    expect(committed).not.toContain('VALUE=DATE')
    expect(committed.match(/DTSTART:\d{8}T\d{6}Z/g)).toHaveLength(GAMES.length)
  })
})
