// The committed schedule against its authority.
//
// src/data/games.js is GENERATED by scripts/build-data.mjs from the frozen
// skeleton in scripts/official.mjs, so these check the MERGE: that the committed
// board still says exactly what the authority says.
//
// NOTE: there is no ESPN cross-check here. The 2027 draw has not happened, so
// there is no men's ESPN feed to freeze and merge against yet (the women's
// capture in test/fixtures/espn-scoreboard.json is a different tournament). When
// FIBA/ESPN publish 2027, restore an ESPN-merge check the way the women's edition
// had one.

import { describe, it, expect } from 'vitest'
import { GAMES } from '../src/data/games.js'
import { EDITION, GROUPS, FLAGS, RANK_ORDER, VENUE_META, OFFICIAL, canon, ALIASES } from '../scripts/official.mjs'
import { ALL_TEAMS } from '../src/data/teams.js'
import { ESPN_ALIASES } from '../src/services/espn.js'

const byNum = new Map(GAMES.map((g) => [g.num, g]))

describe('committed schedule vs the authority', () => {
  it('matches the edition’s headline numbers', () => {
    expect(GAMES).toHaveLength(EDITION.games)
    expect(Object.keys(GROUPS)).toEqual(EDITION.groups)
    expect(EDITION.year).toBe(2023)
    expect(EDITION.provisional).toBe(false)
  })

  it('keeps the authority’s teams, group, venue and tip-off for every first-round game', () => {
    for (const o of OFFICIAL.filter((g) => g.stage === 'R1')) {
      const g = byNum.get(o.num)
      expect(g.t1).toBe(o.t1)
      expect(g.t2).toBe(o.t2)
      expect(g.group).toBe(o.group)
      expect(g.venue).toBe(o.venue)
      expect(g.ko).toBe(o.ko)
    }
  })

  it('keeps the authority’s bracket wiring for every later game', () => {
    for (const o of OFFICIAL.filter((g) => g.stage !== 'R1')) {
      const g = byNum.get(o.num)
      expect(g.stage).toBe(o.stage)
      expect(g.label1).toBe(o.label1)
      expect(g.label2).toBe(o.label2)
      expect(g.venue).toBe(o.venue)
      expect(g.ko).toBe(o.ko)
    }
  })

  it('assigns every game one of the five authoritative venues', () => {
    const keys = new Set(Object.keys(VENUE_META))
    for (const g of GAMES) expect(keys.has(g.venue), `game ${g.num}`).toBe(true)
  })
})

describe('team-name resolution', () => {
  it('gives every team in the draw a flag', () => {
    for (const name of ALL_TEAMS) expect(FLAGS[name], name).toBeTruthy()
  })

  it('ranks exactly the 32 teams in the draw, with no extras', () => {
    expect([...RANK_ORDER].sort()).toEqual([...ALL_TEAMS].sort())
  })

  // ESPN names the sides as we do, so the overlay needs no aliases. The build-time
  // aliases map feed spellings to canonical nation names. Most target a team in this
  // edition's field (USA, Ivory Coast), and every one of those must name a real team.
  // A few are general normalizations for nations that did not qualify in 2023 (e.g.
  // Turkey -> Türkiye), so they resolve without being in the field.
  it('needs no ESPN overlay aliases, and its build aliases canonicalize correctly', () => {
    expect(ESPN_ALIASES).toEqual({})
    for (const [from, to] of Object.entries(ALIASES)) {
      expect(canon(from)).toBe(to)
      if (ALL_TEAMS.includes(to)) {
        expect(FLAGS[to], `${from} -> ${to}`).toBeTruthy()
      }
    }
    // The aliases that DO name a 2023 team resolve to real teams.
    expect(canon('USA')).toBe('United States')
    expect(ALL_TEAMS).toContain('United States')
    expect(canon('Ivory Coast')).toBe("Côte d'Ivoire")
    expect(ALL_TEAMS).toContain("Côte d'Ivoire")
  })
})
