// Build src/data/{teams,venues,games}.js from the frozen authority in
// scripts/official.mjs, which holds the real, completed 2023 FIBA Men's Basketball
// World Cup: every team, group, score, date and venue verified against Wikipedia's
// per-group tables. There is no live feed to overlay (ESPN's fiba slug does not
// serve the 2023 event), so this build is the whole pipeline.
//
// Run with: npm run build:data

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  EDITION,
  GROUPS,
  FLAGS,
  RANK_ORDER,
  VENUE_META,
  officialGames,
} from './official.mjs'

const OUT = join(import.meta.dirname, '..', 'src', 'data')

// IOC / FIBA three-letter codes for the 32 teams. ESPN's own abbreviation field is
// not trusted (it has collided across teams in the women's feed); these are set
// here deliberately, one canonical code per nation.
const ABBR = {
  'United States': 'USA', Serbia: 'SRB', Germany: 'GER', Canada: 'CAN', France: 'FRA',
  Australia: 'AUS', Slovenia: 'SLO', Spain: 'ESP', Greece: 'GRE', Lithuania: 'LTU',
  Latvia: 'LAT', Brazil: 'BRA', Italy: 'ITA', Japan: 'JPN', 'Dominican Republic': 'DOM',
  'New Zealand': 'NZL', 'Puerto Rico': 'PUR', Georgia: 'GEO', Finland: 'FIN',
  'South Sudan': 'SSD', Lebanon: 'LBN', Venezuela: 'VEN', Egypt: 'EGY', Angola: 'ANG',
  "Côte d'Ivoire": 'CIV', Philippines: 'PHI', Jordan: 'JOR', China: 'CHN',
  Montenegro: 'MNE', Mexico: 'MEX', Iran: 'IRI', 'Cape Verde': 'CPV',
}

const RANK_BY_TEAM = Object.fromEntries(RANK_ORDER.map((name, i) => [name, i + 1]))

const banner = (subject) =>
  `// GENERATED by scripts/build-data.mjs, do not edit by hand.\n` +
  `// ${subject}\n` +
  `// The real, completed 2023 tournament, frozen and verified in scripts/official.mjs\n` +
  `// (the authority). Regenerate with: npm run build:data\n`

// ── teams.js ────────────────────────────────────────────────────────────────
function writeTeams() {
  const allNames = Object.values(GROUPS).flat()
  const team = (name) => ({ name, flag: FLAGS[name], abbr: ABBR[name], rank: RANK_BY_TEAM[name] })
  const groupsSrc = Object.entries(GROUPS)
    .map(([g, names]) => {
      const rows = names
        // strongest first within the group, matching the women's convention
        .slice()
        .sort((a, b) => RANK_BY_TEAM[a] - RANK_BY_TEAM[b])
        .map((n) => {
          const t = team(n)
          return `    { name: ${JSON.stringify(t.name)}, flag: '${t.flag}', abbr: '${t.abbr}', rank: ${t.rank} },`
        })
        .join('\n')
      return `  ${g}: [\n${rows}\n  ],`
    })
    .join('\n')

  const flagBy = allNames.map((n) => `  ${JSON.stringify(n)}: '${FLAGS[n]}',`).join('\n')
  const abbrBy = allNames.map((n) => `  ${JSON.stringify(n)}: '${ABBR[n]}',`).join('\n')
  const rankBy = RANK_ORDER.map((n) => `  ${JSON.stringify(n)}: ${RANK_BY_TEAM[n]},`).join('\n')
  const all = [...allNames].sort().map((n) => `  ${JSON.stringify(n)},`).join('\n')

  const src = `${banner(`The ${EDITION.teams} teams of the FIBA Men's Basketball World Cup ${EDITION.year}.`)}
export const TEAMS = {
${groupsSrc}
}

export const FLAG_BY_TEAM = {
${flagBy}
}

export const ABBR_BY_TEAM = {
${abbrBy}
}

export const RANK_BY_TEAM = {
${rankBy}
}

export const ALL_TEAMS = [
${all}
]
`
  writeFileSync(join(OUT, 'teams.js'), src)
}

// ── venues.js ─────────────────────────────────────────────────────────────────
function writeVenues() {
  const entries = Object.values(VENUE_META)
    .map((v) => {
      return (
        `  ${v.key}: {\n` +
        `    name: ${JSON.stringify(v.name)},\n` +
        `    sponsorName: ${JSON.stringify(v.sponsorName)},\n` +
        `    city: ${JSON.stringify(v.city)},\n` +
        `    country: ${JSON.stringify(v.country)},\n` +
        `    countryFlag: '${v.countryFlag}',\n` +
        `    tz: ${JSON.stringify(v.tz)},\n` +
        `    capacity: ${v.capacity},\n` +
        `  },`
      )
    })
    .join('\n')

  const src = `${banner(`The ${EDITION.venues} host arenas of the FIBA Men's Basketball World Cup ${EDITION.year} (Manila, Okinawa and Jakarta; each on its own timezone).`)}
export const VENUES = {
${entries}
}
`
  writeFileSync(join(OUT, 'venues.js'), src)
}

// ── games.js ──────────────────────────────────────────────────────────────────
function gameLine(g) {
  const parts = [`num: ${g.num}`, `stage: ${JSON.stringify(g.stage)}`]
  if (g.group) parts.push(`group: ${JSON.stringify(g.group)}`)
  if (g.classGroup) parts.push(`classGroup: ${JSON.stringify(g.classGroup)}`)
  if (g.classLabel) parts.push(`classLabel: ${JSON.stringify(g.classLabel)}`)
  parts.push(`t1: ${g.t1 == null ? 'null' : JSON.stringify(g.t1)}`)
  parts.push(`t2: ${g.t2 == null ? 'null' : JSON.stringify(g.t2)}`)
  if (g.label1) parts.push(`label1: ${JSON.stringify(g.label1)}`)
  if (g.label2) parts.push(`label2: ${JSON.stringify(g.label2)}`)
  parts.push(`venue: ${JSON.stringify(g.venue)}`)
  parts.push(`ko: ${g.ko == null ? 'null' : JSON.stringify(g.ko)}`)
  if (g.date) parts.push(`date: ${JSON.stringify(g.date)}`)
  if (g.tbdTip) parts.push(`tbdTip: true`)
  if (Array.isArray(g.score)) parts.push(`score: [${g.score[0]}, ${g.score[1]}]`)
  parts.push(`espnId: null`)
  parts.push(`tv: []`)
  return `  { ${parts.join(', ')} },`
}

function writeGames() {
  const games = officialGames()
  const lines = games.map(gameLine).join('\n')
  const src = `${banner(`All ${EDITION.games} games of the FIBA Men's Basketball World Cup ${EDITION.year}.`)}//
// \`stage\`: R1 (first round), R2 (second round), QF/SF/3rd/Final (knockout), Class
// (classification, 17th-32nd and 5th-8th; shown in the schedule but not bracketed).
// \`ko\` is the tip-off instant, stored at each venue's local wall clock (the
// Philippines +08:00, Okinawa +09:00, Jakarta +07:00). \`score\` is the final result
// [t1, t2]. \`label1\`/\`label2\` are the bracket placeholders a game was drawn with;
// they stay alongside the resolved teams. \`espnId\`/\`tv\` are empty (no live feed
// backs a completed 2023 tournament).

export const STAGE_LABELS = {
  R1: 'First Round',
  R2: 'Second Round',
  QF: 'Quarter-Final',
  SF: 'Semi-Final',
  '3rd': 'Third-Place Game',
  Final: 'Final',
  Class: 'Classification',
}

export const STAGE_ORDER = ['R1', 'R2', 'Class', 'QF', 'SF', '3rd', 'Final']

export const GAMES = [
${lines}
]
`
  writeFileSync(join(OUT, 'games.js'), src)
}

writeTeams()
writeVenues()
writeGames()
console.log(`Wrote src/data/{teams,venues,games}.js for FIBA Men's World Cup ${EDITION.year}`)
console.log(`  ${officialGames().length} games, ${Object.values(GROUPS).flat().length} teams, ${Object.keys(VENUE_META).length} venues`)
